# Generated by Django 4.1.4 on 2023-11-18 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('elevator_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_elevator', models.IntegerField(default=1)),
                ('number_of_floors', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_number', models.IntegerField()),
                ('current_floor', models.IntegerField()),
                ('is_door_open', models.BooleanField(default=True)),
                ('direction', models.CharField(max_length=20)),
                ('is_working', models.BooleanField(default=True)),
                ('elevator_system', models.ForeignKey(db_column='elevator_id', on_delete=django.db.models.deletion.CASCADE, to='endpoints.elevatorsystem')),
            ],
        ),
    ]
