# Generated by Django 4.1.4 on 2023-11-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='requests',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.IntegerField(default=1),
        ),
    ]
