# Generated by Django 4.1.4 on 2023-11-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_alter_elevator_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_from_floor', models.IntegerField()),
                ('requested_to_floor', models.IntegerField()),
            ],
        ),
    ]
